### ISSUE TITLE
npm上找不到这个包了

### ISSUE THREAD

**Issue by jerryrat2016** [condorheroblog/html-export-pdf-cli#2]

**Comment by condorheroblog** [comment]
这个代码仓库里面就是最新的代码，已经写完了，但是还没有发布，因为在配合着重写 [vuepress-plugin](https://github.com/condorheroblog/vuepress-plugin) 我想等写完再发布，就在这两天。

**Comment by condorheroblog** [comment]
@jerryrat2016 我已经发布了 https://www.npmjs.com/package/html-export-pdf-cli  ，现在你可以在 `npm` 上安装使用了🥳。
